# docker-compose.override.yml (برای محیط پروداکشن)
# این فایل به طور خودکار توسط `docker compose` بارگذاری می‌شود تا تنظیمات `docker-compose.yml` را override کند.
# برای اجرا در محیط پروداکشن از دستور `docker compose up --build` استفاده کنید.

services:
  web:
    build:
      context: .
      args:
        - DEV=false
    image: ecommerce-api-prod:latest
    container_name: backend
    command: gunicorn ecommerce_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    ports: []
    env_file:
      - .env

  celery_worker:
    image: ecommerce-api-prod:latest
    container_name: celery_worker
    volumes: []
    env_file:
      - .env

  celery_beat:
    image: ecommerce-api-prod:latest
    container_name: celery_beat
    volumes: []
    env_file:
      - .env

  flower:
    image: ecommerce-api-prod:latest
    container_name: flower
    volumes: []
    env_file:
      - .env

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - certbot_www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
      - nginx_cache:/var/cache/nginx
    environment:
      DOMAIN: ${DOMAIN}
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot_www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM;
      certbot certonly --webroot -w /var/www/certbot
      --email ${CERTBOT_EMAIL}
      --agree-tos --no-eff-email
      -d ${DOMAIN} -d www.${DOMAIN};
      while :; do
        certbot renew --webroot -w /var/www/certbot;
        sleep 12h;
      done"

volumes:
  certbot_www:
  letsencrypt:
  nginx_cache:
  static_volume:
  media_volume:
