apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ecommerce-api.fullname" . }}-migration
  labels:
    {{- include "ecommerce-api.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, this
    # job would be created every time we run a helm upgrade.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "ecommerce-api.fullname" . }}-migration
      labels:
        {{- include "ecommerce-api.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "manage.py", "migrate", "--noinput"]
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.name }}
                  key: {{ $value.key }}
            {{- end }}
  backoffLimit: 1
